name: Build Workflow

on:
  push:
    tags:
        - "*"
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      NODE_VERSION: 18
      CARTESI_CLI_VERSION: 0.15.0
      CARTESI_MACHINE_IMAGE_NAME: tribes-machine
      REGISTRY: ghcr.io/${{ github.repository_owner }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3
      - name: Run tests
        run: make test
        env:
          BUILDX_BUILDER: ${{ steps.setup_buildx.outputs.name }}
      - name: Extract metadata from Git refs and GitHub events
        id: extract_metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.CARTESI_MACHINE_IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Install Cartesi CLI
        run: npm i -g @cartesi/cli@${{ env.CARTESI_CLI_VERSION }}
      - name: Build Cartesi Machine Image
        id: build_machine
        run: make build
      - name: Push Cartesi Machine image
        run: |
          docker image tag machine:latest "${{ env.REGISTRY }}/${{ env.CARTESI_MACHINE_IMAGE_NAME }}"
          docker image push --all-tags "${{ env.REGISTRY }}/${{ env.CARTESI_MACHINE_IMAGE_NAME }}"

  # release:
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   permissions:
  #     contents: write
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: Set up Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: stable
  #     - name: Run GoReleaser
  #       uses: goreleaser/goreleaser-action@v6
  #       with:
  #         distribution: goreleaser
  #         version: latest
  #         args: release --clean
  #         workdir: ./cmd/tribes-rollup

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [package]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Trim CHANGELOG.md
        run: sed -e '0,/^##[^#]/d' -e '/^##[^#]/,$d' -i CHANGELOG.md
      - name: Publish Github release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          body_path: CHANGELOG.md

  releases-matrix:
    name: Build binaries for release
    runs-on: ubuntu-latest
    needs: [release]
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64, riscv64]
        exclude:
          - goarch: arm64
            goos: windows
          - goarch: riscv64
            goos: windows
          - goarch: riscv64
            goos: darwin
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          overwrite: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          extra_files: CHANGELOG.md LICENSE README.md